"use client";

import { useEffect, useRef, useState, useCallback } from "react";
import { createClient } from "@/lib/supabase";
import { motion, useScroll, useTransform, useInView, AnimatePresence } from "framer-motion";

const usps = [
  {
    title: "Adaptive",
    body: "The plan moves with your life. Miss a session and it restructures. Race coming up? It tapers. No other affordable plan does this.",
    image: "/steve-lieman-iIFg_WaDZzw-unsplash.jpg",
    imagePosition: "center",
  },
  {
    title: "Science-backed with explanation",
    body: "Not just what to do — but why. Every session has a purpose rooted in real research, not generic templates copied from a coaching book.",
    image: "/pexels-2159477359-36080208.jpg",
    imagePosition: "center",
  },
  {
    title: "Built for athletes by athletes",
    body: "You're not using a faceless app. This was built by a triathlete who lived this exact problem and spent real time solving it. That authenticity is something no corporate fitness platform can replicate.",
    image: "/pexels-cristian-camilo-estrada-2152272341-35757291.jpg",
    imagePosition: "0% center",
  },
  {
    title: "Human-designed. Algorithm-sharpened.",
    body: "Your plan isn't generated by AI — it's built on coach-led, proven training foundations and then personalised by intelligent algorithms. The science is human. The precision is machine.",
    image: "/joshua-tsu-k27fjLXCuuo-unsplash.jpg",
    imagePosition: "center",
  },
];

function USPSlideshow() {
  const [current, setCurrent] = useState(0);
  const [direction, setDirection] = useState(1);

  useEffect(() => {
    const timer = setInterval(() => {
      setDirection(1);
      setCurrent((prev) => (prev + 1) % usps.length);
    }, 6000);
    return () => clearInterval(timer);
  }, []);

  const goTo = (index: number) => {
    setDirection(index > current ? 1 : -1);
    setCurrent(index);
  };

  const variants = {
    enter: (dir: number) => ({ opacity: 0, x: dir > 0 ? 120 : -120 }),
    center: { opacity: 1, x: 0 },
    exit: (dir: number) => ({ opacity: 0, x: dir > 0 ? -120 : 120 }),
  };

  return (
    <div className="relative w-full bg-black text-white h-[280px] flex flex-col justify-end overflow-hidden">
      <AnimatePresence>
        {usps[current].image && (
          <motion.div
            key={usps[current].image}
            className="absolute inset-0 bg-cover"
            style={{ backgroundImage: `url('${usps[current].image}')`, backgroundPosition: usps[current].imagePosition ?? "center" }}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.4 }}
          />
        )}
      </AnimatePresence>
      <div className="absolute inset-0 bg-black/50" />
      <AnimatePresence mode="wait" custom={direction}>
        <motion.div
          key={current}
          custom={direction}
          variants={variants}
          initial="enter"
          animate="center"
          exit="exit"
          transition={{ duration: 0.25, ease: "easeOut" }}
          className="absolute inset-x-0 bottom-24 px-6 md:px-12"
        >
          <motion.h3
            className="text-3xl md:text-4xl font-bold mb-3"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: 0.1 }}
          >
            {usps[current].title}
          </motion.h3>
          <motion.p
            className="text-gray-300 text-base leading-relaxed font-light max-w-2xl"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: 0.2 }}
          >
            {usps[current].body}
          </motion.p>
        </motion.div>
      </AnimatePresence>
      <div className="absolute bottom-6 left-6 md:left-12 right-6 md:right-12 flex items-center justify-between">
        <div className="flex items-center gap-3">
          {usps.map((_, i) => (
            <button
              key={i}
              onClick={() => goTo(i)}
              className={`h-1 rounded-full transition-all duration-300 ${i === current ? "w-8" : "w-4 bg-gray-600"}`}
              style={i === current ? { backgroundColor: "#E9EB9E" } : {}}
            />
          ))}
        </div>
        <div className="flex items-center gap-4">
          <motion.button
            onClick={() => goTo((current - 1 + usps.length) % usps.length)}
            className="text-gray-400 text-2xl leading-none"
            whileHover={{ scale: 1.3, color: "#ffffff" }}
            transition={{ type: "spring", stiffness: 300, damping: 20 }}
          >
            ←
          </motion.button>
          <motion.button
            onClick={() => goTo((current + 1) % usps.length)}
            className="text-gray-400 text-2xl leading-none"
            whileHover={{ scale: 1.3, color: "#ffffff" }}
            transition={{ type: "spring", stiffness: 300, damping: 20 }}
          >
            →
          </motion.button>
        </div>
      </div>
    </div>
  );
}

function PricingModal({ onClose }: { onClose: () => void }) {
  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 flex items-end md:items-center justify-center"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
        <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
        <motion.div
          className="relative bg-white rounded-t-3xl md:rounded-3xl w-full md:max-w-4xl p-8 md:p-12 z-10"
          initial={{ y: 100, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: 100, opacity: 0 }}
          transition={{ type: "spring", stiffness: 300, damping: 30 }}
        >
          <button onClick={onClose} className="absolute top-5 right-6 text-gray-400 hover:text-black text-2xl leading-none">×</button>
          <p className="text-sm uppercase tracking-widest mb-2" style={{ color: "#799496" }}>Pricing</p>
          <h2 className="text-3xl font-bold mb-2">Simple, honest pricing.</h2>
          <p className="text-gray-400 mb-8">No card required. No commitment. Just 30 days free — then £9.99/month.</p>
          <div className="max-w-sm">
            <div className="rounded-2xl p-8 text-white" style={{ backgroundColor: "#14080E" }}>
              <p className="text-4xl font-bold mb-1">Free <span className="text-lg font-normal" style={{ color: "#799496" }}>/ 30 days</span></p>
              <p className="text-sm mb-1" style={{ color: "#799496" }}>Then £9.99/month. Cancel anytime.</p>
              <p className="text-sm mb-8" style={{ color: "#799496" }}>No card required to start.</p>
              <ul className="space-y-3 text-sm text-gray-300 mb-8">
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Fully personalised training plan</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Adaptive — updates when life happens</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Norwegian method periodisation</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Swim, bike and run all covered</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Community access</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Free t-shirt after 3 months</li>
              </ul>
              <motion.a
                href="/signup"
                className="block text-center font-medium px-6 py-3 rounded-full text-sm"
                style={{ backgroundColor: "#E9EB9E", color: "#14080E" }}
                whileHover={{ scale: 1.03 }}
                transition={{ type: "spring", stiffness: 300, damping: 20 }}
              >
                Start free trial
              </motion.a>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

function FadeIn({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 30 }}
      animate={isInView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.7, delay, ease: "easeOut" }}
    >
      {children}
    </motion.div>
  );
}

function WaitlistSection() {
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    const supabase = createClient();
    const { error } = await supabase.from("waitlist").insert({ email, name });

    if (error) {
      if (error.code === "23505") {
        setError("You're already on the list!");
      } else {
        setError("Something went wrong. Please try again.");
      }
      setLoading(false);
      return;
    }

    setSubmitted(true);
    setLoading(false);
  };

  return (
    <section className="relative text-white px-6 md:px-12 py-24 overflow-hidden" style={{ backgroundImage: "url('/joshua-tsu-k27fjLXCuuo-unsplash.jpg')", backgroundSize: "cover", backgroundPosition: "center" }}>
      <div className="absolute inset-0 bg-black/60" />
      <div className="relative z-10 max-w-xl">
        <FadeIn>
          <p className="text-sm uppercase tracking-widest mb-4" style={{ color: "#799496" }}>Early access</p>
          <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-4">
            Be the first to train smarter.
          </h2>
          <p className="text-gray-400 text-lg font-light mb-8">
            Join the waitlist and get early access plus a free extended trial when we launch.
          </p>
          {submitted ? (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white/10 rounded-2xl px-6 py-5"
            >
              <p className="text-white font-medium">You&apos;re on the list.</p>
              <p className="text-gray-400 text-sm mt-1">We&apos;ll be in touch when early access opens.</p>
            </motion.div>
          ) : (
            <form onSubmit={handleSubmit} className="flex flex-col gap-3">
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
                placeholder="What should we call you?"
                className="bg-white/10 border border-white/20 rounded-full px-5 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-white transition-colors"
              />
              <div className="flex flex-col md:flex-row gap-3">
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  placeholder="your@email.com"
                  className="flex-1 bg-white/10 border border-white/20 rounded-full px-5 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-white transition-colors"
                />
                <motion.button
                  type="submit"
                  disabled={loading}
                  className="px-6 py-3 rounded-full text-sm font-medium disabled:opacity-50"
                  style={{ backgroundColor: "#E9EB9E", color: "#14080E" }}
                  whileHover={{ scale: 1.03 }}
                  transition={{ type: "spring", stiffness: 300, damping: 20 }}
                >
                  {loading ? "Joining..." : "Join waitlist"}
                </motion.button>
              </div>
            </form>
          )}
          {error && <p className="text-red-400 text-sm mt-3">{error}</p>}
        </FadeIn>

        <FadeIn>
          <div className="mt-16 pt-10 border-t border-white/10">
            <p className="text-sm uppercase tracking-widest text-gray-400 mb-3">Got questions?</p>
            <p className="text-white text-lg font-light mb-4">
              Whether it&apos;s about training, the platform, or just triathlon in general — we&apos;re always up for the conversation.
            </p>
            <a
              href="mailto:hello@thenorwegianeffect.com"
              className="inline-block text-sm text-white underline underline-offset-4 hover:text-gray-300 transition-colors"
            >
              hello@thenorwegianeffect.com
            </a>
          </div>
        </FadeIn>
      </div>
    </section>
  );
}

const heroImages = [
  "/james-lee-_QvszySFByg-unsplash.jpg",
  "/joshua-tsu-k27fjLXCuuo-unsplash.jpg",
];

export default function Home() {
  const [pricingOpen, setPricingOpen] = useState(false);
  const [heroIndex, setHeroIndex] = useState(0);
  const heroRef = useRef(null);
  const { scrollY } = useScroll();
  const imageY = useTransform(scrollY, [0, 600], [0, 150]);
  const textY = useTransform(scrollY, [0, 600], [0, -60]);

  useEffect(() => {
    const interval = setInterval(() => {
      setHeroIndex((i) => (i + 1) % heroImages.length);
    }, 30000);
    return () => clearInterval(interval);
  }, []);

  return (
    <main className="min-h-screen bg-white text-black">
      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 py-5 md:px-12 bg-white/80 backdrop-blur-sm border-b border-gray-100">
        <span className="text-2xl font-semibold tracking-tight" style={{ fontFamily: "var(--font-playfair)" }}>the norwegian effect.</span>
        <div className="flex items-center gap-6 text-sm">
          <a href="#science" className="hidden md:block text-gray-500 hover:text-black transition-colors">The Method</a>
          <button onClick={() => setPricingOpen(true)} className="hidden md:block text-gray-500 hover:text-black transition-colors">Pricing</button>
          <a href="/login" className="hidden md:block text-gray-500 hover:text-black transition-colors">Log in</a>
          <a href="/signup" className="bg-[#49475B] text-white px-4 py-2 rounded-full hover:bg-[#14080E] transition-colors">
            Get started
          </a>
        </div>
      </nav>

      {/* Hero */}
      <section ref={heroRef} className="relative min-h-screen flex items-center overflow-hidden">
        <AnimatePresence>
          <motion.div
            key={heroIndex}
            className="absolute inset-0 bg-cover bg-center scale-110"
            style={{ backgroundImage: `url('${heroImages[heroIndex]}')`, y: imageY }}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 1.5 }}
          />
        </AnimatePresence>
        <div className="absolute inset-0" style={{ background: "rgba(20,8,14,0.6)" }} />
        <div className="absolute inset-0" style={{ backgroundImage: "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='1'/%3E%3C/svg%3E\")", opacity: 0.12, mixBlendMode: "overlay" }} />
        <motion.div
          className="relative z-10 px-6 md:px-12 pt-24 max-w-4xl"
          style={{ y: textY }}
        >
          <motion.p
            className="text-sm uppercase tracking-widest text-gray-300 mb-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            Science-backed, adaptive endurance sport training plan
          </motion.p>
          <motion.h1
            className="text-4xl md:text-5xl font-bold leading-tight tracking-tight mb-8 text-white"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.9, delay: 0.4 }}
          >
            It's about<br />the process.
          </motion.h1>
          <motion.p
            className="text-lg md:text-xl text-gray-300 max-w-xl mb-10 leading-relaxed font-light"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.6 }}
          >
            Coach-led foundations, Norwegian methodology, personalised by intelligent algorithms — not generated by AI, but sharpened by it. Built around your goals, your schedule, your life.
          </motion.p>
          <motion.div
            className="flex items-center gap-4"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.8 }}
          >
            <motion.a
              href="/signup"
              className="bg-[#E9EB9E] text-[#14080E] px-6 py-3 rounded-full text-sm font-medium"
              whileHover={{ scale: 1.05 }}
              transition={{ type: "spring", stiffness: 300, damping: 20 }}
            >
              Start your plan
            </motion.a>
            <a href="#science" className="text-sm text-gray-300 hover:text-white transition-colors underline underline-offset-4">
              How it works
            </a>
          </motion.div>
        </motion.div>
      </section>

      {/* Training Methods */}
      <section className="px-6 md:px-12 py-24" style={{ backgroundColor: "#f9f9f9" }}>
        <div className="max-w-4xl">
          <FadeIn>
            <p className="text-sm uppercase tracking-widest mb-4" style={{ color: "#799496" }}>Your method</p>
            <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-4">Your plan. Your method.</h2>
            <p className="text-gray-500 font-light text-lg mb-12">Every athlete is different. That&apos;s why when you sign up, we match you to a training method built specifically for your level, your hours, and your goals.</p>
          </FadeIn>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[
              {
                level: "Beginner",
                hours: "5–6 hrs/week",
                points: ["Effort-based, no data required", "Build consistency across all three disciplines", "Designed to get you to the finish line"],
              },
              {
                level: "Intermediate",
                hours: "7–9 hrs/week",
                points: ["Zone 2 base with structured hard efforts", "Heart rate monitoring", "Eliminate grey zone training"],
              },
              {
                level: "Amateur",
                hours: "8–10 hrs/week",
                points: ["Polarized 80/20 training", "HR or power zones", "Structured annual plan around your race calendar"],
              },
              {
                level: "Semi-Pro",
                hours: "12–15 hrs/week",
                points: ["Threshold-dominant, high volume", "Exact training zones", "Built for near-professional commitment"],
              },
            ].map((plan, i) => (
              <FadeIn key={plan.level} delay={i * 0.1}>
                <motion.a
                  href="/signup"
                  className="block rounded-2xl p-6 border h-full cursor-pointer"
                  style={{ borderColor: "rgba(121,148,150,0.25)" }}
                  whileHover={{ y: -6, boxShadow: "0 12px 32px rgba(0,0,0,0.1)", borderColor: "#49475B" }}
                  transition={{ type: "spring", stiffness: 300, damping: 20 }}
                >
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-xl font-bold">{plan.level}</h3>
                    <span className="text-sm px-3 py-1 rounded-full" style={{ backgroundColor: "#14080E", color: "#E9EB9E" }}>{plan.hours}</span>
                  </div>
                  <ul className="space-y-2">
                    {plan.points.map((point) => (
                      <li key={point} className="flex items-start gap-2 text-sm text-gray-500">
                        <span className="mt-0.5 shrink-0" style={{ color: "#ACC196" }}>✓</span>
                        {point}
                      </li>
                    ))}
                  </ul>
                </motion.a>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>

      {/* Why us */}
      <section className="relative px-6 md:px-12 py-24 overflow-hidden">
        <div className="absolute inset-0" style={{ backgroundImage: "url('/17-a-running-tracks-example-2.jpg')", backgroundSize: "cover", backgroundPosition: "center" }} />
        <div className="absolute inset-0" style={{ backgroundColor: "rgba(73,71,91,0.93)" }} />
        <div className="relative z-10 max-w-3xl">
          <FadeIn>
            <p className="text-sm uppercase tracking-widest mb-4" style={{ color: "#ACC196" }}>Why us</p>
            <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-12 text-white">Why choose the norwegian effect?</h2>
          </FadeIn>
          <div className="space-y-10">
            {[
              {
                title: "Plans that actually fit your life",
                body: "Most training plans assume you have unlimited time and zero commitments. We don't. Your plan is built around your weekly hours, your race date, and your real schedule — and it adjusts when life gets in the way.",
              },
              {
                title: "The science, explained",
                body: "You'll never just be told what to do. Every session has a purpose, and we explain it. Zone 2, threshold work, recovery weeks — you'll understand the why behind every kilometre.",
              },
              {
                title: "A community that gets it",
                body: "Training is better when you're not doing it alone. Ask questions, share sessions, find people at every level who understand the obsession.",
              },
            ].map((item, i) => (
              <FadeIn key={item.title} delay={i * 0.15}>
                <div className="flex gap-6 items-start">
                  <span className="text-sm font-bold mt-1 shrink-0" style={{ color: "#E9EB9E" }}>0{i + 1}</span>
                  <div>
                    <h3 className="text-xl font-bold mb-2 text-white">{item.title}</h3>
                    <p className="font-light leading-relaxed" style={{ color: "#c8c8d4" }}>{item.body}</p>
                  </div>
                </div>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>

      {/* Stats bar */}
      <section className="border-t border-b px-6 md:px-12 py-10" style={{ borderColor: "rgba(121,148,150,0.25)" }}>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          {[
            { stat: "Z2", label: "Norwegian method at its core" },
            { stat: "3", label: "Disciplines, one adaptive plan" },
            { stat: "100%", label: "Tailored to your schedule" },
            { stat: "Live", label: "Plan adapts when life happens" },
          ].map((item, i) => (
            <FadeIn key={item.stat} delay={i * 0.1}>
              <p className="text-3xl font-bold">{item.stat}</p>
              <p className="text-sm mt-1" style={{ color: "#799496" }}>{item.label}</p>
            </FadeIn>
          ))}
        </div>
      </section>

      {/* USP Slideshow */}
      <section className="w-full">
        <USPSlideshow />
      </section>

      {/* Community */}
      <section id="community" className="px-6 md:px-12 py-24">
        <div className="max-w-3xl">
          <FadeIn>
            <p className="text-sm uppercase tracking-widest mb-4" style={{ color: "#799496" }}>Community</p>
            <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-8">
              A community of like-minded athletes.
            </h2>
          </FadeIn>
          <FadeIn delay={0.15}>
            <p className="text-gray-500 text-lg leading-relaxed mb-6 font-light">
              The norwegian effect is more than a training platform — it&apos;s a place to belong. Whether you&apos;re lining up for your first sprint triathlon or chasing a sub-10 Ironman, you&apos;re training alongside people who get it.
            </p>
          </FadeIn>
          <FadeIn delay={0.25}>
            <p className="text-gray-500 text-lg leading-relaxed mb-6 font-light">
              Share sessions, swap race tips, ask the questions Google just can&apos;t answer. This is a space built for honest conversation — about training, nutrition, gear, and the mental side of endurance sport that nobody talks about enough. From your first open water swim to your tenth finish line, every level belongs here.
            </p>
          </FadeIn>
          <FadeIn delay={0.35}>
            <p className="text-gray-500 text-lg leading-relaxed font-light">
              Same goals. Same obsession. Different starting points. That&apos;s the community.
            </p>
          </FadeIn>
        </div>
      </section>

      {/* Portrait images */}
      <section className="py-24 px-6 md:px-12">
        <div className="flex flex-col md:flex-row justify-center gap-6">
        {[
          { src: "/maksym-tymchyk-4yC5nR1PZa0-unsplash.jpg", label: "go deeper." },
          { src: "/kirsten-frank-EWdxx8m1uh4-unsplash.jpg", label: "go harder." },
          { src: "/nick-gosset-3DJfakd6VoU-unsplash.jpg", label: "go further." },
        ].map(({ src, label }, i) => (
          <FadeIn key={src} delay={i * 0.15}>
            <div className="relative w-full md:w-72 h-72 md:h-96 overflow-hidden rounded-2xl">
              <img
                src={src}
                alt="Athlete training"
                className="w-full h-full object-cover"
              />
              <div className="absolute inset-0 rounded-2xl" style={{ background: "radial-gradient(ellipse at center, transparent 40%, rgba(0,0,0,0.6) 100%)" }} />
              <div className="absolute inset-0 flex items-end justify-center pb-8 px-4">
                <p className="text-3xl font-bold text-white text-center drop-shadow-lg">{label}</p>
              </div>
            </div>
          </FadeIn>
        ))}
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="px-6 md:px-12 py-24 bg-gray-50">
        <div className="max-w-sm">
          <FadeIn>
            <p className="text-sm uppercase tracking-widest mb-4" style={{ color: "#799496" }}>Pricing</p>
            <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-2">Simple, honest pricing</h2>
            <p className="text-gray-400 mb-8">30 days free. No card required. Then £9.99/month.</p>
          </FadeIn>
          <FadeIn delay={0.2}>
            <div className="rounded-2xl p-8 text-white" style={{ backgroundColor: "#14080E" }}>
              <p className="text-4xl font-bold mb-1">Free <span className="text-lg font-normal" style={{ color: "#799496" }}>/ 30 days</span></p>
              <p className="text-sm mb-8" style={{ color: "#799496" }}>Then £9.99/month. Cancel anytime.</p>
              <ul className="space-y-3 text-sm text-gray-300 mb-8">
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Fully personalised training plan</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Adaptive — updates when life happens</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Norwegian method periodisation</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Swim, bike and run all covered</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Community access</li>
                <li className="flex items-center gap-2"><span style={{ color: "#ACC196" }}>✓</span> Free t-shirt after 3 months</li>
              </ul>
              <motion.a
                href="/signup"
                className="block text-center font-medium px-6 py-3 rounded-full text-sm"
                style={{ backgroundColor: "#E9EB9E", color: "#14080E" }}
                whileHover={{ scale: 1.05 }}
                transition={{ type: "spring", stiffness: 300, damping: 20 }}
              >
                Start free trial
              </motion.a>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* Founder Story */}
      <section className="px-6 md:px-12 py-24">
        <div className="flex flex-col md:flex-row gap-16 items-start max-w-5xl">
          <FadeIn>
            <div className="w-64 flex-shrink-0 overflow-hidden rounded-2xl">
              <img
                src="/oliver.png"
                alt="Oliver Maltby"
                className="w-full h-auto object-cover grayscale"
              />
            </div>
          </FadeIn>
          <div className="max-w-2xl">
          <FadeIn>
            <p className="text-sm uppercase tracking-widest mb-4" style={{ color: "#799496" }}>Founder</p>
            <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-12">my story</h2>
          </FadeIn>
          <FadeIn delay={0.1}>
            <p className="text-gray-500 text-lg leading-relaxed font-light mb-6">
              I started training for triathlon in 2022. No background in endurance sport, no coach, no idea what I was doing — just a desire to see how far I could push myself.
            </p>
          </FadeIn>
          <FadeIn delay={0.2}>
            <p className="text-gray-500 text-lg leading-relaxed font-light mb-6">
              When I started preparing for my first half ironman, I hit a wall that had nothing to do with fitness. Every training plan I found was either too expensive, too rigid, or completely disconnected from real life. I&apos;m a university student. I have work and late nights.
            </p>
          </FadeIn>
          <FadeIn delay={0.3}>
            <p className="text-gray-500 text-lg leading-relaxed font-light mb-6">
              I&apos;d finish training blocks feeling like I&apos;d either destroyed myself or left too much on the table. Never the balance. I&apos;d read about zone 2, I knew I needed threshold work in between, but nobody was explaining why — just telling me what to do. I needed to understand the science, not just follow instructions.
            </p>
          </FadeIn>
          <FadeIn delay={0.4}>
            <p className="text-gray-500 text-lg leading-relaxed font-light mb-6">
              So I started researching. Books, papers and interviews with coaches and athletes at every level. What came from this wasn&apos;t a copy of any single method — it was a plan built from the ground up, incorporating the best of what actually works. The Norwegian approach to aerobic development is part of that. So is an honest understanding of recovery, periodisation, and what an intermediate athlete&apos;s body can sustain week to week.
            </p>
          </FadeIn>
          <FadeIn delay={0.5}>
            <p className="text-gray-500 text-lg leading-relaxed font-light mb-10">
              I built this because I genuinely couldn&apos;t find it anywhere else. If you&apos;re anything like me — juggling training around a real life, wanting to understand the why behind every session, and tired of plans that don&apos;t bend — then this was made for you.
            </p>
            <p className="font-medium" style={{ color: "#49475B" }}>— Oliver Maltby, London</p>
          </FadeIn>
          </div>
        </div>
      </section>

      {/* Waitlist */}
      <WaitlistSection />

      {/* Footer */}
      <footer className="px-6 md:px-12 py-10 border-t" style={{ borderColor: "rgba(121,148,150,0.25)" }}>
        <div className="flex items-center justify-between">
          <span className="text-sm font-medium" style={{ fontFamily: "var(--font-playfair)" }}>the norwegian effect</span>
          <p className="text-sm text-gray-400">© 2026</p>
        </div>
      </footer>
      {pricingOpen && <PricingModal onClose={() => setPricingOpen(false)} />}
    </main>
  );
}
